chore: common configs support
MapColonies/heartbeat-manager pull request #10
Opened 2021-12-30 11:51 UTC by CL-SHLOMIKONCHA

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2021-12-30 11:56 UTC, asafMasa approved these changes

2022-01-02 07:35 UTC, yossiz16 commented on helm/local.yaml
> +    host: "10.8.1.4"
please remove

2022-01-02 07:35 UTC, yossiz16 commented on helm/local.yaml
> +  imagePullSecretName: acr-registry
remove

2022-01-02 07:35 UTC, yossiz16 commented on helm/local.yaml
> +global:
remove

2022-01-02 07:36 UTC, yossiz16 requested changes
please remove actuall values

2022-01-03 07:33 UTC, Yossizz approved these changes

2022-01-03 08:00 UTC, merged