feat: changes for new common job-manager umbrella and new build and push (MAPCO-4080)
MapColonies/heartbeat-manager pull request #29
Opened 2024-03-25 07:38 UTC by almog8k

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

2024-03-25 15:02 UTC, asafMasa requested changes

2024-03-25 15:02 UTC, asafMasa commented on helm/templates/_tplValues.tpl
> +{{- end -}}
please check EOF in all files

2024-03-25 15:02 UTC, asafMasa commented on helm/values.yaml
> +    name: "common"
keep empty to be overrided from shared-deployments

2024-03-25 15:02 UTC, asafMasa commented on helm/values.yaml
> +  sslEnabled: false
keep empty to be overrided from shared-deployments

2024-03-26 09:31 UTC, almog8k commented on helm/output
> +---
deleted

2024-03-26 14:55 UTC, asafMasa approved these changes

2024-03-28 09:40 UTC, netanelC requested changes
1. In workflows, remove the whitespaces from the last line if the files.
2. Remove the _resources.tpl

2024-03-31 10:44 UTC, netanelC approved these changes

2024-03-31 14:39 UTC, merged