feat: added get-heartbeat route
MapColonies/heartbeat-manager pull request #32
Opened 2024-07-24 13:19 UTC by nitzanmorr

Added the heartbeat get route to allow the job manager to find tasks that never had a heartbeat.

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

2024-07-24 14:09 UTC, CL-SHLOMIKONCHA commented on openapi3.yaml
> +      description: task to log/get heartbeat for
get the last heartbeat by id

2024-07-24 14:28 UTC, CL-SHLOMIKONCHA commented on src/DAL/repositories/heartbeatRepository.ts
> +    async getHeartbeat(_id: string): Promise<HeartbeatEntity | null> {
camelCase parameters is the best practice, _id => id

2024-07-24 14:36 UTC, CL-SHLOMIKONCHA commented on openapi3.yaml
>          type: string
add 'format: uuid'
![image](https://github.com/user-attachments/assets/32046dc8-7b2a-499f-b8d8-2c13b68593ae)

2024-07-24 14:38 UTC, CL-SHLOMIKONCHA commented on openapi3.yaml
> +        'message:':
fix this quotes

2024-07-24 14:39 UTC, CL-SHLOMIKONCHA commented on src/DAL/repositories/heartbeatRepository.ts
> +        id: Equal(_id),
what is the added value of the `Equal` function?
can work the same this way as well:
![image](https://github.com/user-attachments/assets/06da6c78-0c68-4b62-a632-82c93a78ecf8)

2024-07-24 15:00 UTC, CL-SHLOMIKONCHA commented on src/heartbeat/models/heartbeatManager.ts
> +export interface IgetHeartbeatResponse {
IgetHeartbeatResponse => IGetHeartbeatResponse

2024-07-24 15:29 UTC, nitzanmorr commented on openapi3.yaml
>          type: string
added

2024-07-25 10:40 UTC, netanelC requested changes

2024-07-25 10:40 UTC, netanelC commented on tests/integration/heartbeat/heartbeat.spec.ts
> +      const id = '513a40b2-783f-4c82-bd1a-5b6a7aca75d5';
Use [faker](https://www.npmjs.com/package/@faker-js/faker) package in order to generate uuid instead of putting hard-coded values

2024-07-25 10:40 UTC, netanelC commented on tests/integration/heartbeat/heartbeat.spec.ts
> +    describe('Sad path', function () {
"Sad path" mostly refers to 500+ error codes.
```suggestion
    describe('Bad path', function () {
```

2024-07-25 10:40 UTC, CL-SHLOMIKONCHA commented on src/heartbeat/controllers/heartbeatController.ts
> +      if (record === null) {
move this condition to the 'heartbeatManager.ts' file inside GetHeartBeatById function to keep controller clean as we can

2024-07-25 10:40 UTC, CL-SHLOMIKONCHA commented on src/heartbeat/controllers/heartbeatController.ts
> +      if (record === null) {
![image](https://github.com/user-attachments/assets/5dc49a15-1873-47e8-b0ef-413295c4286d)

2024-07-25 10:41 UTC, CL-SHLOMIKONCHA commented on src/heartbeat/controllers/heartbeatController.ts
> +      if (record === null) {
![image](https://github.com/user-attachments/assets/7f8e8c3f-f0c2-41a8-a41c-9343bbac4b25)

2024-07-25 10:47 UTC, CL-SHLOMIKONCHA commented on src/heartbeat/controllers/heartbeatController.ts
> +      if (record === null) {
and add req.id to the info log

2024-07-27 20:11 UTC, netanelC approved these changes

2024-07-29 07:50 UTC, CL-SHLOMIKONCHA commented on tests/integration/heartbeat/heartbeat.spec.ts
> +        requestSender.removeHeartbeats([id]);
now that we use 'uuid' remove heartbeats seems unnecessary

2024-07-29 08:14 UTC, CL-SHLOMIKONCHA commented on tests/integration/heartbeat/heartbeat.spec.ts
> +        requestSender.removeHeartbeats([id]);
irelevent

2024-07-29 08:14 UTC, CL-SHLOMIKONCHA approved these changes

2024-07-29 08:14 UTC, CL-SHLOMIKONCHA commented
Good job!

2024-07-29 08:28 UTC, merged